" Name:         WWDC17
" Description:  Colorful light color scheme for Vim inspired by Apple's WWDC17 page
" Author:       Lifepillar <lifepillar@lifepillar.me>
" URL:          https://github.com/lifepillar/vim-wwdc17-theme
" License:      MIT
" Last Change:  2025 Jun 04

" Generated by Colortemplate v3.0.0-beta5

set background=light

hi clear
let g:colors_name = 'wwdc17'

let s:t_Co = has('gui_running') ? 16777216 : str2nr(&t_Co)

let g:terminal_ansi_colors = ['#5f5f61', '#e8503f', '#00998c', '#d87900', '#527f8f', '#db2d45', '#159ccc', '#f0f0f0', '#888888', '#d87900', '#abb96e', '#e1ad0b', '#8c61a6', '#eb314b', '#23bce1', '#fafafa']

if has('nvim')
  let g:terminal_color_0  = '#5f5f61'
  let g:terminal_color_1  = '#e8503f'
  let g:terminal_color_2  = '#00998c'
  let g:terminal_color_3  = '#d87900'
  let g:terminal_color_4  = '#527f8f'
  let g:terminal_color_5  = '#db2d45'
  let g:terminal_color_6  = '#159ccc'
  let g:terminal_color_7  = '#f0f0f0'
  let g:terminal_color_8  = '#888888'
  let g:terminal_color_9  = '#d87900'
  let g:terminal_color_10 = '#abb96e'
  let g:terminal_color_11 = '#e1ad0b'
  let g:terminal_color_12 = '#8c61a6'
  let g:terminal_color_13 = '#eb314b'
  let g:terminal_color_14 = '#23bce1'
  let g:terminal_color_15 = '#fafafa'
endif

let s:frame = abs(get(g:, 'wwdc17_frame_color', 10)) % 16
let s:italic = has('gui_running') || has('nvim') || (&t_ZH != '' && &t_ZH != '[7m' && !has('win32'))
let s:transp_bg = get(g:, 'wwdc17_transp_bg', 0)
let s:transp_italic = (s:italic ? 1 : 0) + 2 * s:transp_bg

hi! link Conditional Statement
hi! link CurSearch Search
hi! link CursorLineFold FoldColumn
hi! link CursorLineSign SignColumn
hi! link Define PreProc
hi! link Exception Statement
hi! link LineNrAbove LineNr
hi! link LineNrBelow LineNr
hi! link Macro PreProc
hi! link PmenuMatch Pmenu
hi! link PmenuMatchSel PmenuSel
hi! link PopupNotification WarningMsg
hi! link PopupSelected PmenuSel
hi! link PreCondit PreProc
hi! link QuickFixLine Search
hi! link Repeat Statement
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link TabPanel TabLine
hi! link TabPanelFill TabPanelFill
hi! link TabPanelSel TabePanelSel
hi! link Tag Special
hi! link TermCursor Cursor
hi! link Typedef Type
hi! link debugBreakpoint SignColumn
hi! link debugPC SignColumn
hi! link lCursor Cursor

hi Normal guifg=#5f5f61 guibg=#fafafa guisp=NONE gui=NONE ctermfg=59 ctermbg=231 cterm=NONE term=NONE
hi Added guifg=#00998c guibg=NONE guisp=NONE gui=italic ctermfg=30 ctermbg=NONE cterm=italic term=bold
hi Boolean guifg=#abb96e guibg=NONE guisp=NONE gui=NONE ctermfg=143 ctermbg=NONE cterm=NONE term=NONE
hi Changed guifg=#527f8f guibg=NONE guisp=NONE gui=bold,italic ctermfg=66 ctermbg=NONE cterm=bold,italic term=bold,italic
hi Character guifg=#db2d45 guibg=NONE guisp=NONE gui=NONE ctermfg=197 ctermbg=NONE cterm=NONE term=NONE
hi ColorColumn guifg=NONE guibg=#f0f0f0 guisp=NONE gui=NONE ctermfg=NONE ctermbg=255 cterm=NONE term=reverse
hi CommandMode guifg=#db2d45 guibg=#fafafa guisp=NONE gui=reverse ctermfg=197 ctermbg=231 cterm=reverse term=reverse
hi Comment guifg=#888888 guibg=NONE guisp=NONE gui=italic ctermfg=102 ctermbg=NONE cterm=italic term=italic
hi Conceal guifg=#00998c guibg=NONE guisp=NONE gui=NONE ctermfg=30 ctermbg=NONE cterm=NONE term=NONE
hi Constant guifg=#00998c guibg=NONE guisp=NONE gui=NONE ctermfg=30 ctermbg=NONE cterm=NONE term=bold,italic
hi Cursor guifg=NONE guibg=NONE guisp=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse term=NONE
hi CursorColumn guifg=NONE guibg=#f0f0f0 guisp=NONE gui=NONE ctermfg=NONE ctermbg=255 cterm=NONE term=reverse
hi CursorIM guifg=NONE guibg=#fafafa guisp=NONE gui=NONE ctermfg=NONE ctermbg=231 cterm=NONE term=NONE
hi CursorLine guifg=NONE guibg=#f0f0f0 guisp=NONE gui=NONE ctermfg=NONE ctermbg=255 cterm=NONE term=underline
hi CursorLineNr guifg=#d87900 guibg=#f0f0f0 guisp=NONE gui=NONE ctermfg=172 ctermbg=255 cterm=NONE term=bold,italic,reverse,underline
hi Debug guifg=#db2d45 guibg=NONE guisp=NONE gui=NONE ctermfg=197 ctermbg=NONE cterm=NONE term=NONE
hi Delimiter guifg=#527f8f guibg=NONE guisp=NONE gui=NONE ctermfg=66 ctermbg=NONE cterm=NONE term=NONE
hi DiffAdd guifg=#abb96e guibg=#5f5f61 guisp=NONE gui=reverse ctermfg=143 ctermbg=59 cterm=reverse term=reverse,underline
hi DiffChange guifg=#d87900 guibg=#fafafa guisp=NONE gui=reverse ctermfg=172 ctermbg=231 cterm=reverse term=reverse,underline
hi DiffDelete guifg=#e8503f guibg=#fafafa guisp=NONE gui=reverse ctermfg=167 ctermbg=231 cterm=reverse term=reverse,underline
hi DiffText guifg=#159ccc guibg=#fafafa guisp=NONE gui=bold,reverse ctermfg=74 ctermbg=231 cterm=bold,reverse term=bold,reverse,underline
hi Directory guifg=#00998c guibg=NONE guisp=NONE gui=NONE ctermfg=30 ctermbg=NONE cterm=NONE term=NONE
hi EndOfBuffer guifg=#d87900 guibg=NONE guisp=NONE gui=NONE ctermfg=172 ctermbg=NONE cterm=NONE term=NONE
hi Error guifg=#e8503f guibg=#fafafa guisp=NONE gui=reverse ctermfg=167 ctermbg=231 cterm=reverse term=reverse
hi ErrorMsg guifg=#e8503f guibg=#fafafa guisp=NONE gui=reverse ctermfg=167 ctermbg=231 cterm=reverse term=bold,italic,reverse
hi Float guifg=#abb96e guibg=NONE guisp=NONE gui=NONE ctermfg=143 ctermbg=NONE cterm=NONE term=NONE
hi FoldColumn guifg=#888888 guibg=#f0f0f0 guisp=NONE gui=NONE ctermfg=102 ctermbg=255 cterm=NONE term=reverse
hi Folded guifg=#888888 guibg=#f0f0f0 guisp=NONE gui=italic ctermfg=102 ctermbg=255 cterm=italic term=italic,reverse,underline
hi Function guifg=#00998c guibg=NONE guisp=NONE gui=NONE ctermfg=30 ctermbg=NONE cterm=NONE term=NONE
hi Identifier guifg=#527f8f guibg=NONE guisp=NONE gui=NONE ctermfg=66 ctermbg=NONE cterm=NONE term=italic
hi Ignore guifg=#d87900 guibg=NONE guisp=NONE gui=NONE ctermfg=172 ctermbg=NONE cterm=NONE term=NONE
hi IncSearch guifg=#d87900 guibg=#fafafa guisp=NONE gui=standout ctermfg=172 ctermbg=231 cterm=reverse term=bold,italic,reverse
hi Include guifg=#8c61a6 guibg=NONE guisp=NONE gui=NONE ctermfg=97 ctermbg=NONE cterm=NONE term=NONE
hi InsertMode guifg=#abb96e guibg=#fafafa guisp=NONE gui=reverse ctermfg=143 ctermbg=231 cterm=reverse term=reverse
hi Keyword guifg=#159ccc guibg=NONE guisp=NONE gui=NONE ctermfg=74 ctermbg=NONE cterm=NONE term=NONE
hi Label guifg=#00998c guibg=NONE guisp=NONE gui=NONE ctermfg=30 ctermbg=NONE cterm=NONE term=NONE
hi LineNr guifg=#888888 guibg=#f0f0f0 guisp=NONE gui=NONE ctermfg=102 ctermbg=255 cterm=NONE term=reverse
hi MatchParen guifg=NONE guibg=NONE guisp=#5f5f61 gui=bold,underline ctermfg=NONE ctermbg=NONE cterm=bold,underline term=bold,underline
hi ModeMsg guifg=#5f5f61 guibg=NONE guisp=NONE gui=NONE ctermfg=59 ctermbg=NONE cterm=NONE term=NONE
hi MoreMsg guifg=#d87900 guibg=NONE guisp=NONE gui=NONE ctermfg=172 ctermbg=NONE cterm=NONE term=NONE
hi NonText guifg=#888888 guibg=NONE guisp=NONE gui=NONE ctermfg=102 ctermbg=NONE cterm=NONE term=NONE
hi NormalMode guifg=#888888 guibg=#fafafa guisp=NONE gui=reverse ctermfg=102 ctermbg=231 cterm=reverse term=reverse
hi Number guifg=#00998c guibg=NONE guisp=NONE gui=NONE ctermfg=30 ctermbg=NONE cterm=NONE term=NONE
hi Operator guifg=#159ccc guibg=NONE guisp=NONE gui=NONE ctermfg=74 ctermbg=NONE cterm=NONE term=NONE
hi Pmenu guifg=#5f5f61 guibg=#f0f0f0 guisp=NONE gui=NONE ctermfg=59 ctermbg=255 cterm=NONE term=reverse
hi PmenuSbar guifg=#d87900 guibg=#888888 guisp=NONE gui=NONE ctermfg=172 ctermbg=102 cterm=NONE term=NONE
hi PmenuSel guifg=#fafafa guibg=#d87900 guisp=NONE gui=NONE ctermfg=231 ctermbg=172 cterm=NONE term=NONE
hi PmenuThumb guifg=#e8503f guibg=#d87900 guisp=NONE gui=NONE ctermfg=167 ctermbg=172 cterm=NONE term=NONE
hi PreProc guifg=#e8503f guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE term=italic
hi Question guifg=#5f5f61 guibg=NONE guisp=NONE gui=NONE ctermfg=59 ctermbg=NONE cterm=NONE term=standout
hi Removed guifg=#e8503f guibg=NONE guisp=NONE gui=bold,italic,strikethrough ctermfg=167 ctermbg=NONE cterm=bold,italic,strikethrough term=reverse,strikethrough
hi ReplaceMode guifg=#d87900 guibg=#fafafa guisp=NONE gui=reverse ctermfg=172 ctermbg=231 cterm=reverse term=reverse
hi Search guifg=#e1ad0b guibg=#fafafa guisp=NONE gui=reverse ctermfg=178 ctermbg=231 cterm=reverse term=italic,underline
hi SignColumn guifg=#d87900 guibg=NONE guisp=NONE gui=NONE ctermfg=172 ctermbg=NONE cterm=NONE term=reverse
hi Special guifg=#e8503f guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE term=bold,italic
hi SpecialChar guifg=#db2d45 guibg=NONE guisp=NONE gui=NONE ctermfg=197 ctermbg=NONE cterm=NONE term=NONE
hi SpecialComment guifg=#db2d45 guibg=NONE guisp=NONE gui=NONE ctermfg=197 ctermbg=NONE cterm=NONE term=NONE
hi SpecialKey guifg=#d87900 guibg=NONE guisp=NONE gui=NONE ctermfg=172 ctermbg=NONE cterm=NONE term=bold
hi SpellBad guifg=#db2d45 guibg=NONE guisp=#888888 gui=undercurl ctermfg=197 ctermbg=NONE cterm=underline term=italic,underline
hi SpellCap guifg=#db2d45 guibg=NONE guisp=#888888 gui=undercurl ctermfg=197 ctermbg=NONE cterm=underline term=italic,underline
hi SpellLocal guifg=#db2d45 guibg=NONE guisp=#888888 gui=undercurl ctermfg=197 ctermbg=NONE cterm=underline term=italic,underline
hi SpellRare guifg=#db2d45 guibg=NONE guisp=#888888 gui=undercurl ctermfg=197 ctermbg=NONE cterm=underline term=italic,underline
hi Statement guifg=#159ccc guibg=NONE guisp=NONE gui=NONE ctermfg=74 ctermbg=NONE cterm=NONE term=bold
hi StatusLine guifg=#abb96e guibg=#fafafa guisp=NONE gui=bold,reverse ctermfg=143 ctermbg=231 cterm=bold,reverse term=bold,reverse
hi StatusLineNC guifg=#abb96e guibg=#f0f0f0 guisp=NONE gui=reverse ctermfg=143 ctermbg=255 cterm=reverse term=reverse
hi StorageClass guifg=#159ccc guibg=NONE guisp=NONE gui=NONE ctermfg=74 ctermbg=NONE cterm=NONE term=NONE
hi String guifg=#d87900 guibg=NONE guisp=NONE gui=NONE ctermfg=172 ctermbg=NONE cterm=NONE term=NONE
hi Structure guifg=#e8503f guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE term=NONE
hi TabLine guifg=#f0f0f0 guibg=#abb96e guisp=NONE gui=NONE ctermfg=255 ctermbg=143 cterm=NONE term=italic,reverse,underline
hi TabLineFill guifg=#fafafa guibg=#abb96e guisp=NONE gui=NONE ctermfg=231 ctermbg=143 cterm=NONE term=reverse,underline
hi TabLineSel guifg=#fafafa guibg=#abb96e guisp=NONE gui=bold ctermfg=231 ctermbg=143 cterm=bold term=bold
hi TermCursorNC guifg=#fafafa guibg=#5f5f61 guisp=NONE gui=NONE ctermfg=231 ctermbg=59 cterm=NONE term=NONE
hi Terminal guifg=#5f5f61 guibg=#fafafa guisp=NONE gui=NONE ctermfg=59 ctermbg=231 cterm=NONE term=NONE
hi Title guifg=#d87900 guibg=NONE guisp=NONE gui=bold ctermfg=172 ctermbg=NONE cterm=bold term=bold
hi Todo guifg=#db2d45 guibg=NONE guisp=NONE gui=bold ctermfg=197 ctermbg=NONE cterm=bold term=bold,underline
hi ToolbarButton guifg=#5f5f61 guibg=#f0f0f0 guisp=NONE gui=bold ctermfg=59 ctermbg=255 cterm=bold term=bold,reverse
hi ToolbarLine guifg=#888888 guibg=#f0f0f0 guisp=NONE gui=NONE ctermfg=102 ctermbg=255 cterm=NONE term=reverse
hi Type guifg=#8c61a6 guibg=NONE guisp=NONE gui=NONE ctermfg=97 ctermbg=NONE cterm=NONE term=bold
hi Underlined guifg=NONE guibg=NONE guisp=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline term=underline
hi VertSplit guifg=#f0f0f0 guibg=#abb96e guisp=NONE gui=NONE ctermfg=255 ctermbg=143 cterm=NONE term=reverse
hi Visual guifg=#527f8f guibg=#fafafa guisp=NONE gui=reverse ctermfg=66 ctermbg=231 cterm=reverse term=reverse
hi VisualMode guifg=#527f8f guibg=#fafafa guisp=NONE gui=reverse ctermfg=66 ctermbg=231 cterm=reverse term=reverse
hi VisualNOS guifg=#fafafa guibg=#527f8f guisp=NONE gui=NONE ctermfg=231 ctermbg=66 cterm=NONE term=NONE
hi WarningMsg guifg=#e8503f guibg=NONE guisp=NONE gui=NONE ctermfg=167 ctermbg=NONE cterm=NONE term=standout
hi WildMenu guifg=#fafafa guibg=#db2d45 guisp=NONE gui=bold ctermfg=231 ctermbg=197 cterm=bold term=bold

if has('gui_running') || (has('termguicolors') && &termguicolors)
  if s:frame == 0
    hi StatusLine guifg=#5f5f61
    hi StatusLineNC guifg=#5f5f61
    hi TabLine guibg=#5f5f61
    hi TabLineFill guibg=#5f5f61
    hi TabLineSel guibg=#5f5f61
    hi VertSplit guibg=#5f5f61
  elseif s:frame == 1
    hi StatusLine guifg=#e8503f
    hi StatusLineNC guifg=#e8503f
    hi TabLine guibg=#e8503f
    hi TabLineFill guibg=#e8503f
    hi TabLineSel guibg=#d87900
    hi VertSplit guibg=#e8503f
    hi WildMenu guibg=#abb96e
  elseif s:frame == 11
    hi StatusLine guifg=#e1ad0b
    hi StatusLineNC guifg=#e1ad0b
    hi TabLine guibg=#e1ad0b
    hi TabLineFill guibg=#e1ad0b
    hi TabLineSel guibg=#e1ad0b
    hi VertSplit guibg=#e1ad0b
  elseif s:frame == 12
    hi StatusLine guifg=#8c61a6
    hi StatusLineNC guifg=#8c61a6
    hi TabLine guibg=#8c61a6
    hi TabLineFill guibg=#8c61a6
    hi TabLineSel guibg=#8c61a6
    hi VertSplit guibg=#8c61a6
  elseif s:frame == 13
    hi StatusLine guifg=#eb314b
    hi StatusLineNC guifg=#eb314b
    hi TabLine guibg=#eb314b
    hi TabLineFill guifg=#f0f0f0 guibg=#eb314b
    hi TabLineSel guibg=#eb314b
    hi VertSplit guibg=#eb314b
    hi WildMenu guibg=#d87900
  elseif s:frame == 14
    hi StatusLine guifg=#23bce1
    hi StatusLineNC guifg=#23bce1
    hi TabLine guibg=#23bce1
    hi TabLineFill guibg=#23bce1
    hi TabLineSel guibg=#23bce1
    hi VertSplit guibg=#23bce1
  elseif s:frame == 15
    hi StatusLine guifg=#fafafa guibg=#5f5f61
    hi StatusLineNC guifg=#fafafa guibg=#888888
    hi TabLine guifg=#888888 guibg=#fafafa
    hi TabLineFill guifg=#888888 guibg=#fafafa
    hi TabLineSel guifg=#5f5f61 guibg=#fafafa
    hi VertSplit guifg=#888888 guibg=#fafafa
    hi WildMenu guibg=#888888
  elseif s:frame == 2
    hi StatusLine guifg=#00998c
    hi StatusLineNC guifg=#00998c
    hi TabLine guibg=#00998c
    hi TabLineFill guibg=#00998c
    hi TabLineSel guibg=#00998c
    hi VertSplit guibg=#00998c
  elseif s:frame == 3
    hi StatusLine guifg=#d87900
    hi StatusLineNC guifg=#d87900
    hi TabLine guibg=#d87900
    hi TabLineFill guibg=#d87900
    hi TabLineSel guibg=#d87900
    hi VertSplit guibg=#d87900
  elseif s:frame == 4
    hi StatusLine guifg=#527f8f
    hi StatusLineNC guifg=#527f8f
    hi TabLine guifg=#fafafa guibg=#527f8f
    hi TabLineFill guibg=#527f8f
    hi TabLineSel guibg=#527f8f
    hi VertSplit guibg=#527f8f
  elseif s:frame == 5
    hi StatusLine guifg=#db2d45
    hi StatusLineNC guifg=#db2d45
    hi TabLine guibg=#db2d45
    hi TabLineFill guifg=#f0f0f0 guibg=#db2d45
    hi TabLineSel guibg=#db2d45
    hi VertSplit guibg=#db2d45
    hi WildMenu guibg=#d87900 guisp=NONE gui=NONE cterm=NONE
  elseif s:frame == 6
    hi StatusLine guifg=#159ccc
    hi StatusLineNC guifg=#159ccc
    hi TabLine guibg=#159ccc
    hi TabLineFill guibg=#159ccc
    hi TabLineSel guibg=#159ccc
    hi VertSplit guibg=#159ccc
  elseif s:frame == 7
    hi StatusLine guifg=#f0f0f0 guibg=#5f5f61
    hi StatusLineNC guifg=#f0f0f0 guibg=#888888
    hi TabLine guifg=#888888 guibg=#f0f0f0
    hi TabLineFill guifg=#5f5f61 guibg=#f0f0f0
    hi TabLineSel guifg=#5f5f61 guibg=#f0f0f0
    hi VertSplit guifg=#888888 guibg=#f0f0f0
  elseif s:frame == 8
    hi StatusLine guifg=#888888
    hi StatusLineNC guifg=#888888
    hi TabLine guibg=#888888
    hi TabLineFill guibg=#888888
    hi TabLineSel guibg=#888888
    hi VertSplit guibg=#888888
  elseif s:frame == 9
    hi StatusLine guifg=#d87900
    hi StatusLineNC guifg=#d87900
    hi TabLine guibg=#d87900
    hi TabLineFill guibg=#d87900
    hi TabLineSel guibg=#d87900
    hi VertSplit guibg=#d87900
    hi WildMenu guibg=#abb96e
  endif
endif

if s:t_Co >= 256
  if s:frame == 0
    hi StatusLine ctermfg=59
    hi StatusLineNC ctermfg=59
    hi TabLine ctermbg=59
    hi TabLineFill ctermbg=59
    hi TabLineSel ctermbg=59
    hi VertSplit ctermbg=59
  elseif s:frame == 1
    hi StatusLine ctermfg=167
    hi StatusLineNC ctermfg=167
    hi TabLine ctermbg=167
    hi TabLineFill ctermbg=167
    hi TabLineSel ctermbg=172
    hi VertSplit ctermbg=167
    hi WildMenu ctermbg=143
  elseif s:frame == 11
    hi StatusLine ctermfg=178
    hi StatusLineNC ctermfg=178
    hi TabLine ctermbg=178
    hi TabLineFill ctermbg=178
    hi TabLineSel ctermbg=178
    hi VertSplit ctermbg=178
  elseif s:frame == 12
    hi StatusLine ctermfg=97
    hi StatusLineNC ctermfg=97
    hi TabLine ctermbg=97
    hi TabLineFill ctermbg=97
    hi TabLineSel ctermbg=97
    hi VertSplit ctermbg=97
  elseif s:frame == 13
    hi StatusLine ctermfg=197
    hi StatusLineNC ctermfg=197
    hi TabLine ctermbg=197
    hi TabLineFill ctermfg=255 ctermbg=197
    hi TabLineSel ctermbg=197
    hi VertSplit ctermbg=197
    hi WildMenu ctermbg=172
  elseif s:frame == 14
    hi StatusLine ctermfg=38
    hi StatusLineNC ctermfg=38
    hi TabLine ctermbg=38
    hi TabLineFill ctermbg=38
    hi TabLineSel ctermbg=38
    hi VertSplit ctermbg=38
  elseif s:frame == 15
    hi StatusLine ctermfg=231 ctermbg=59
    hi StatusLineNC ctermfg=231 ctermbg=102
    hi TabLine ctermfg=102 ctermbg=231
    hi TabLineFill ctermfg=102 ctermbg=231
    hi TabLineSel ctermfg=59 ctermbg=231
    hi VertSplit ctermfg=102 ctermbg=231
    hi WildMenu ctermbg=102
  elseif s:frame == 2
    hi StatusLine ctermfg=30
    hi StatusLineNC ctermfg=30
    hi TabLine ctermbg=30
    hi TabLineFill ctermbg=30
    hi TabLineSel ctermbg=30
    hi VertSplit ctermbg=30
  elseif s:frame == 3
    hi StatusLine ctermfg=172
    hi StatusLineNC ctermfg=172
    hi TabLine ctermbg=172
    hi TabLineFill ctermbg=172
    hi TabLineSel ctermbg=172
    hi VertSplit ctermbg=172
  elseif s:frame == 4
    hi StatusLine ctermfg=66
    hi StatusLineNC ctermfg=66
    hi TabLine ctermfg=231 ctermbg=66
    hi TabLineFill ctermbg=66
    hi TabLineSel ctermbg=66
    hi VertSplit ctermbg=66
  elseif s:frame == 5
    hi StatusLine ctermfg=197
    hi StatusLineNC ctermfg=197
    hi TabLine ctermbg=197
    hi TabLineFill ctermfg=255 ctermbg=197
    hi TabLineSel ctermbg=197
    hi VertSplit ctermbg=197
    hi WildMenu ctermbg=172 cterm=NONE
  elseif s:frame == 6
    hi StatusLine ctermfg=74
    hi StatusLineNC ctermfg=74
    hi TabLine ctermbg=74
    hi TabLineFill ctermbg=74
    hi TabLineSel ctermbg=74
    hi VertSplit ctermbg=74
  elseif s:frame == 7
    hi StatusLine ctermfg=255 ctermbg=59
    hi StatusLineNC ctermfg=255 ctermbg=102
    hi TabLine ctermfg=102 ctermbg=255
    hi TabLineFill ctermfg=59 ctermbg=255
    hi TabLineSel ctermfg=59 ctermbg=255
    hi VertSplit ctermfg=102 ctermbg=255
  elseif s:frame == 8
    hi StatusLine ctermfg=102
    hi StatusLineNC ctermfg=102
    hi TabLine ctermbg=102
    hi TabLineFill ctermbg=102
    hi TabLineSel ctermbg=102
    hi VertSplit ctermbg=102
  elseif s:frame == 9
    hi StatusLine ctermfg=172
    hi StatusLineNC ctermfg=172
    hi TabLine ctermbg=172
    hi TabLineFill ctermbg=172
    hi TabLineSel ctermbg=172
    hi VertSplit ctermbg=172
    hi WildMenu ctermbg=143
  endif
  if s:italic == 0
    hi Added cterm=NONE
    hi Changed cterm=NONE
    hi Comment cterm=NONE
    hi Removed cterm=bold,strikethrough
  endif
  if s:transp_bg == 1
    hi Normal ctermbg=NONE
    hi CursorLine ctermbg=NONE cterm=underline
    hi CursorLineNr ctermbg=NONE
    hi FoldColumn ctermbg=NONE
    hi LineNr ctermbg=NONE
    hi Terminal ctermbg=NONE
  endif
  if s:transp_italic == 0
    hi Folded cterm=NONE
  elseif s:transp_italic == 2
    hi Folded ctermbg=NONE cterm=NONE
  elseif s:transp_italic == 3
    hi Folded ctermbg=NONE cterm=italic
  endif
  unlet s:frame
  unlet s:italic
  unlet s:transp_bg
  unlet s:transp_italic
  finish
endif

if s:t_Co >= 8
  hi Normal ctermfg=Black ctermbg=White cterm=NONE
  hi Added ctermfg=DarkGreen ctermbg=NONE cterm=italic
  hi Boolean ctermfg=Green ctermbg=NONE cterm=NONE
  hi Changed ctermfg=DarkBlue ctermbg=NONE cterm=bold,italic
  hi Character ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi ColorColumn ctermfg=NONE ctermbg=Gray cterm=NONE
  hi CommandMode ctermfg=DarkMagenta ctermbg=White cterm=reverse
  hi Comment ctermfg=DarkGray ctermbg=NONE cterm=italic
  hi Conceal ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Constant ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=Gray cterm=NONE
  hi CursorIM ctermfg=NONE ctermbg=White cterm=NONE
  hi CursorLine ctermfg=NONE ctermbg=Gray cterm=NONE
  hi CursorLineNr ctermfg=Red ctermbg=Gray cterm=NONE
  hi Debug ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi DiffAdd ctermfg=Green ctermbg=Black cterm=reverse
  hi DiffChange ctermfg=DarkYellow ctermbg=White cterm=reverse
  hi DiffDelete ctermfg=DarkRed ctermbg=White cterm=reverse
  hi DiffText ctermfg=DarkCyan ctermbg=White cterm=bold,reverse
  hi Directory ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=Red ctermbg=NONE cterm=NONE
  hi Error ctermfg=DarkRed ctermbg=White cterm=reverse
  hi ErrorMsg ctermfg=DarkRed ctermbg=White cterm=reverse
  hi Float ctermfg=Green ctermbg=NONE cterm=NONE
  hi FoldColumn ctermfg=DarkGray ctermbg=Gray cterm=NONE
  hi Folded ctermfg=DarkGray ctermbg=Gray cterm=italic
  hi Function ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi IncSearch ctermfg=Red ctermbg=White cterm=reverse
  hi Include ctermfg=Blue ctermbg=NONE cterm=NONE
  hi InsertMode ctermfg=Green ctermbg=White cterm=reverse
  hi Keyword ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Label ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi LineNr ctermfg=DarkGray ctermbg=Gray cterm=NONE
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi ModeMsg ctermfg=Black ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=Red ctermbg=NONE cterm=NONE
  hi NonText ctermfg=DarkGray ctermbg=NONE cterm=NONE
  hi NormalMode ctermfg=DarkGray ctermbg=White cterm=reverse
  hi Number ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Operator ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=Black ctermbg=Gray cterm=NONE
  hi PmenuSbar ctermfg=Red ctermbg=DarkGray cterm=NONE
  hi PmenuSel ctermfg=White ctermbg=Red cterm=NONE
  hi PmenuThumb ctermfg=DarkRed ctermbg=Red cterm=NONE
  hi PreProc ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Question ctermfg=Black ctermbg=NONE cterm=NONE
  hi Removed ctermfg=DarkRed ctermbg=NONE cterm=bold,italic,strikethrough
  hi ReplaceMode ctermfg=Red ctermbg=White cterm=reverse
  hi Search ctermfg=Yellow ctermbg=White cterm=reverse
  hi SignColumn ctermfg=Red ctermbg=NONE cterm=NONE
  hi Special ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=Red ctermbg=NONE cterm=NONE
  hi SpellBad cterm=underline
  hi SpellCap cterm=underline
  hi SpellLocal cterm=underline
  hi SpellRare cterm=underline
  hi Statement ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi StatusLine ctermfg=Green ctermbg=White cterm=bold,reverse
  hi StatusLineNC ctermfg=Green ctermbg=Gray cterm=reverse
  hi StorageClass ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi String ctermfg=Red ctermbg=NONE cterm=NONE
  hi Structure ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi TabLine ctermfg=Gray ctermbg=Green cterm=NONE
  hi TabLineFill ctermfg=White ctermbg=Green cterm=NONE
  hi TabLineSel ctermfg=White ctermbg=Green cterm=bold
  hi TermCursorNC ctermfg=White ctermbg=Black cterm=NONE
  hi Terminal ctermfg=Black ctermbg=White cterm=NONE
  hi Title ctermfg=Red ctermbg=NONE cterm=bold
  hi Todo ctermfg=DarkMagenta ctermbg=NONE cterm=bold
  hi ToolbarButton ctermfg=Black ctermbg=Gray cterm=bold
  hi ToolbarLine ctermfg=DarkGray ctermbg=Gray cterm=NONE
  hi Type ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi VertSplit ctermfg=Gray ctermbg=Green cterm=NONE
  hi Visual ctermfg=DarkBlue ctermbg=White cterm=reverse
  hi VisualMode ctermfg=DarkBlue ctermbg=White cterm=reverse
  hi VisualNOS ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi WarningMsg ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi WildMenu ctermfg=White ctermbg=DarkMagenta cterm=bold
  if s:frame == 0
    hi StatusLine ctermfg=Black
    hi StatusLineNC ctermfg=Black
    hi TabLine ctermbg=Black
    hi TabLineFill ctermbg=Black
    hi TabLineSel ctermbg=Black
    hi VertSplit ctermbg=Black
  elseif s:frame == 1
    hi StatusLine ctermfg=DarkRed
    hi StatusLineNC ctermfg=DarkRed
    hi TabLine ctermbg=DarkRed
    hi TabLineFill ctermbg=DarkRed
    hi TabLineSel ctermbg=Red
    hi VertSplit ctermbg=DarkRed
    hi WildMenu ctermbg=Green
  elseif s:frame == 11
    hi StatusLine ctermfg=Yellow
    hi StatusLineNC ctermfg=Yellow
    hi TabLine ctermbg=Yellow
    hi TabLineFill ctermbg=Yellow
    hi TabLineSel ctermbg=Yellow
    hi VertSplit ctermbg=Yellow
  elseif s:frame == 12
    hi StatusLine ctermfg=Blue
    hi StatusLineNC ctermfg=Blue
    hi TabLine ctermbg=Blue
    hi TabLineFill ctermbg=Blue
    hi TabLineSel ctermbg=Blue
    hi VertSplit ctermbg=Blue
  elseif s:frame == 13
    hi StatusLine ctermfg=Magenta
    hi StatusLineNC ctermfg=Magenta
    hi TabLine ctermbg=Magenta
    hi TabLineFill ctermfg=Gray ctermbg=Magenta
    hi TabLineSel ctermbg=Magenta
    hi VertSplit ctermbg=Magenta
    hi WildMenu ctermbg=DarkYellow
  elseif s:frame == 14
    hi StatusLine ctermfg=Cyan
    hi StatusLineNC ctermfg=Cyan
    hi TabLine ctermbg=Cyan
    hi TabLineFill ctermbg=Cyan
    hi TabLineSel ctermbg=Cyan
    hi VertSplit ctermbg=Cyan
  elseif s:frame == 15
    hi StatusLine ctermfg=White ctermbg=Black
    hi StatusLineNC ctermfg=White ctermbg=DarkGray
    hi TabLine ctermfg=DarkGray ctermbg=White
    hi TabLineFill ctermfg=DarkGray ctermbg=White
    hi TabLineSel ctermfg=Black ctermbg=White
    hi VertSplit ctermfg=DarkGray ctermbg=White
    hi WildMenu ctermbg=DarkGray
  elseif s:frame == 2
    hi StatusLine ctermfg=DarkGreen
    hi StatusLineNC ctermfg=DarkGreen
    hi TabLine ctermbg=DarkGreen
    hi TabLineFill ctermbg=DarkGreen
    hi TabLineSel ctermbg=DarkGreen
    hi VertSplit ctermbg=DarkGreen
  elseif s:frame == 3
    hi StatusLine ctermfg=DarkYellow
    hi StatusLineNC ctermfg=DarkYellow
    hi TabLine ctermbg=DarkYellow
    hi TabLineFill ctermbg=DarkYellow
    hi TabLineSel ctermbg=DarkYellow
    hi VertSplit ctermbg=DarkYellow
  elseif s:frame == 4
    hi StatusLine ctermfg=DarkBlue
    hi StatusLineNC ctermfg=DarkBlue
    hi TabLine ctermfg=White ctermbg=DarkBlue
    hi TabLineFill ctermbg=DarkBlue
    hi TabLineSel ctermbg=DarkBlue
    hi VertSplit ctermbg=DarkBlue
  elseif s:frame == 5
    hi StatusLine ctermfg=DarkMagenta
    hi StatusLineNC ctermfg=DarkMagenta
    hi TabLine ctermbg=DarkMagenta
    hi TabLineFill ctermfg=Gray ctermbg=DarkMagenta
    hi TabLineSel ctermbg=DarkMagenta
    hi VertSplit ctermbg=DarkMagenta
    hi WildMenu ctermbg=DarkYellow cterm=NONE
  elseif s:frame == 6
    hi StatusLine ctermfg=DarkCyan
    hi StatusLineNC ctermfg=DarkCyan
    hi TabLine ctermbg=DarkCyan
    hi TabLineFill ctermbg=DarkCyan
    hi TabLineSel ctermbg=DarkCyan
    hi VertSplit ctermbg=DarkCyan
  elseif s:frame == 7
    hi StatusLine ctermfg=Gray ctermbg=Black
    hi StatusLineNC ctermfg=Gray ctermbg=DarkGray
    hi TabLine ctermfg=DarkGray ctermbg=Gray
    hi TabLineFill ctermfg=Black ctermbg=Gray
    hi TabLineSel ctermfg=Black ctermbg=Gray
    hi VertSplit ctermfg=DarkGray ctermbg=Gray
  elseif s:frame == 8
    hi StatusLine ctermfg=DarkGray
    hi StatusLineNC ctermfg=DarkGray
    hi TabLine ctermbg=DarkGray
    hi TabLineFill ctermbg=DarkGray
    hi TabLineSel ctermbg=DarkGray
    hi VertSplit ctermbg=DarkGray
  elseif s:frame == 9
    hi StatusLine ctermfg=Red
    hi StatusLineNC ctermfg=Red
    hi TabLine ctermbg=Red
    hi TabLineFill ctermbg=Red
    hi TabLineSel ctermbg=Red
    hi VertSplit ctermbg=Red
    hi WildMenu ctermbg=Green
  endif
  if s:italic == 0
    hi Added cterm=NONE
    hi Changed cterm=NONE
    hi Comment cterm=NONE
    hi Removed cterm=bold,strikethrough
  endif
  if s:transp_bg == 1
    hi Normal ctermbg=NONE
    hi CursorLine ctermbg=NONE cterm=underline
    hi CursorLineNr ctermbg=NONE
    hi FoldColumn ctermbg=NONE
    hi LineNr ctermbg=NONE
    hi Terminal ctermbg=NONE
  endif
  if s:transp_italic == 0
    hi Folded cterm=NONE
  elseif s:transp_italic == 2
    hi Folded ctermbg=NONE cterm=NONE
  elseif s:transp_italic == 3
    hi Folded ctermbg=NONE cterm=italic
  endif
  unlet s:frame
  unlet s:italic
  unlet s:transp_bg
  unlet s:transp_italic
  finish
endif

if s:t_Co >= 0
  hi LineNrAbove term=reverse
  hi LineNrBelow term=reverse
  hi PopupNotification term=NONE
  hi StatusLineTerm term=bold,reverse
  hi StatusLineTermNC term=reverse
  hi TabPanel term=italic,reverse,underline
  hi TabPanelFill term=reverse,underline
  hi TabPanelSel term=bold
  unlet s:frame
  unlet s:italic
  unlet s:transp_bg
  unlet s:transp_italic
  finish
endif

" vim: et ts=8 sw=2 sts=2
