" Name:         WWDC17
" Description:  Colorful light color scheme for Vim inspired by Apple's WWDC17 page
" Author:       Lifepillar <lifepillar@lifepillar.me>
" Maintainer:   Lifepillar <lifepillar@lifepillar.me>
" Website:      https://github.com/lifepillar/vim-wwdc17-theme
" License:      MIT
" Last Updated: Sun Nov 15 22:44:24 2020

" Generated by Colortemplate v2.1.0

set background=light

hi clear
let g:colors_name = 'wwdc17'

let s:t_Co = exists('&t_Co') && !empty(&t_Co) && &t_Co > 1 ? &t_Co : 2
let s:italics = (&t_ZH != '' && &t_ZH != '[7m') || has('gui_running') || has('nvim')

hi! link QuickFixLine Search
hi! link StatusLineTerm StatusLine
hi! link StatusLineTermNC StatusLineNC
hi! link Conditional Statement
hi! link Define PreProc
hi! link Exception Statement
hi! link Macro PreProc
hi! link PreCondit PreProc
hi! link Repeat Statement
hi! link Tag Special
hi! link Typedef Type
hi! link lCursor Cursor

if (has('termguicolors') && &termguicolors) || has('gui_running')
  let g:terminal_ansi_colors = ['#5f5f61', '#e8503f', '#00998c', '#d87900',
        \ '#527f8f', '#db2d45', '#159ccc', '#f0f0f0', '#888888', '#d87900',
        \ '#abb96e', '#e1ad0b', '#8c61a6', '#eb314b', '#23bce1', '#fafafa']
  if has('nvim')
    let g:terminal_color_0 = '#5f5f61'
    let g:terminal_color_1 = '#e8503f'
    let g:terminal_color_2 = '#00998c'
    let g:terminal_color_3 = '#d87900'
    let g:terminal_color_4 = '#527f8f'
    let g:terminal_color_5 = '#db2d45'
    let g:terminal_color_6 = '#159ccc'
    let g:terminal_color_7 = '#f0f0f0'
    let g:terminal_color_8 = '#888888'
    let g:terminal_color_9 = '#d87900'
    let g:terminal_color_10 = '#abb96e'
    let g:terminal_color_11 = '#e1ad0b'
    let g:terminal_color_12 = '#8c61a6'
    let g:terminal_color_13 = '#eb314b'
    let g:terminal_color_14 = '#23bce1'
    let g:terminal_color_15 = '#fafafa'
  endif
  if get(g:, 'wwdc17_transp_bg', 0) && !has('gui_running')
    hi Normal guifg=#5f5f61 guibg=NONE gui=NONE cterm=NONE
    hi CursorLine guifg=NONE guibg=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
    hi CursorLineNr guifg=#d87900 guibg=NONE gui=NONE cterm=NONE
    hi Folded guifg=#888888 guibg=NONE gui=italic cterm=italic
    hi LineNr guifg=#888888 guibg=NONE gui=NONE cterm=NONE
    hi FoldColumn guifg=#888888 guibg=NONE gui=NONE cterm=NONE
    hi Terminal guifg=#5f5f61 guibg=NONE gui=NONE cterm=NONE
    if !s:italics
      hi Folded gui=NONE cterm=NONE
    endif
  else
    hi Normal guifg=#5f5f61 guibg=#fafafa gui=NONE cterm=NONE
    hi CursorLine guifg=NONE guibg=#f0f0f0 gui=NONE cterm=NONE
    hi CursorLineNr guifg=#d87900 guibg=#f0f0f0 gui=NONE cterm=NONE
    hi Folded guifg=#888888 guibg=#f0f0f0 gui=italic cterm=italic
    hi LineNr guifg=#888888 guibg=#f0f0f0 gui=NONE cterm=NONE
    hi FoldColumn guifg=#888888 guibg=#f0f0f0 gui=NONE cterm=NONE
    hi Terminal guifg=#5f5f61 guibg=#fafafa gui=NONE cterm=NONE
    if !s:italics
      hi Folded gui=NONE cterm=NONE
    endif
  endif
  hi ColorColumn guifg=NONE guibg=#f0f0f0 gui=NONE cterm=NONE
  hi Conceal guifg=#00998c guibg=NONE gui=NONE cterm=NONE
  hi Cursor guifg=NONE guibg=NONE gui=reverse ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn guifg=NONE guibg=#f0f0f0 gui=NONE cterm=NONE
  hi DiffAdd guifg=#abb96e guibg=#5f5f61 gui=reverse cterm=reverse
  hi DiffChange guifg=#d87900 guibg=#fafafa gui=reverse cterm=reverse
  hi DiffDelete guifg=#e8503f guibg=#fafafa gui=reverse cterm=reverse
  hi DiffText guifg=#159ccc guibg=#fafafa gui=bold,reverse cterm=bold,reverse
  hi Directory guifg=#00998c guibg=NONE gui=NONE cterm=NONE
  hi EndOfBuffer guifg=#d87900 guibg=NONE gui=NONE cterm=NONE
  hi ErrorMsg guifg=#e8503f guibg=#fafafa gui=reverse cterm=reverse
  hi IncSearch guifg=#d87900 guibg=#fafafa gui=standout cterm=reverse
  hi MatchParen guifg=NONE guibg=NONE guisp=#5f5f61 gui=bold,underline ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi ModeMsg guifg=#5f5f61 guibg=NONE gui=NONE cterm=NONE
  hi MoreMsg guifg=#d87900 guibg=NONE gui=NONE cterm=NONE
  hi NonText guifg=#888888 guibg=NONE gui=NONE cterm=NONE
  hi Pmenu guifg=#5f5f61 guibg=#f0f0f0 gui=NONE cterm=NONE
  hi PmenuSbar guifg=#d87900 guibg=#888888 gui=NONE cterm=NONE
  hi PmenuSel guifg=#fafafa guibg=#d87900 gui=NONE cterm=NONE
  hi PmenuThumb guifg=#e8503f guibg=#d87900 gui=NONE cterm=NONE
  hi Question guifg=#5f5f61 guibg=NONE gui=NONE cterm=NONE
  hi Search guifg=#e1ad0b guibg=#fafafa gui=reverse cterm=reverse
  hi SignColumn guifg=#d87900 guibg=NONE gui=NONE cterm=NONE
  hi SpecialKey guifg=#d87900 guibg=NONE gui=NONE cterm=NONE
  hi SpellBad guifg=#db2d45 guibg=NONE guisp=#888888 gui=undercurl cterm=underline
  hi SpellCap guifg=#db2d45 guibg=NONE guisp=#888888 gui=undercurl cterm=underline
  hi SpellLocal guifg=#db2d45 guibg=NONE guisp=#888888 gui=undercurl cterm=underline
  hi SpellRare guifg=#db2d45 guibg=NONE guisp=#888888 gui=undercurl cterm=underline
  hi Title guifg=#d87900 guibg=NONE gui=bold cterm=bold
  hi Visual guifg=#527f8f guibg=#fafafa gui=reverse cterm=reverse
  hi VisualNOS guifg=#fafafa guibg=#527f8f gui=NONE cterm=NONE
  hi WarningMsg guifg=#e8503f guibg=NONE gui=NONE cterm=NONE
  let s:fc = abs(get(g:, 'wwdc17_frame_color', 10)) % 16
  if s:fc == 0
    hi StatusLine guifg=#5f5f61 guibg=#fafafa gui=bold,reverse cterm=bold,reverse
    hi StatusLineNC guifg=#5f5f61 guibg=#f0f0f0 gui=reverse cterm=reverse
    hi TabLine guifg=#f0f0f0 guibg=#5f5f61 gui=NONE cterm=NONE
    hi TabLineFill guifg=#fafafa guibg=#5f5f61 gui=NONE cterm=NONE
    hi TabLineSel guifg=#fafafa guibg=#5f5f61 gui=bold cterm=bold
    hi VertSplit guifg=#f0f0f0 guibg=#5f5f61 gui=NONE cterm=NONE
    hi WildMenu guifg=#fafafa guibg=#db2d45 gui=bold cterm=bold
  elseif s:fc == 1
    hi StatusLine guifg=#e8503f guibg=#fafafa gui=bold,reverse cterm=bold,reverse
    hi StatusLineNC guifg=#e8503f guibg=#f0f0f0 gui=reverse cterm=reverse
    hi TabLine guifg=#f0f0f0 guibg=#e8503f gui=NONE cterm=NONE
    hi TabLineFill guifg=#fafafa guibg=#e8503f gui=NONE cterm=NONE
    hi TabLineSel guifg=#fafafa guibg=#d87900 gui=bold cterm=bold
    hi VertSplit guifg=#f0f0f0 guibg=#e8503f gui=NONE cterm=NONE
    hi WildMenu guifg=#fafafa guibg=#abb96e gui=bold cterm=bold
  elseif s:fc == 2
    hi StatusLine guifg=#00998c guibg=#fafafa gui=bold,reverse cterm=bold,reverse
    hi StatusLineNC guifg=#00998c guibg=#f0f0f0 gui=reverse cterm=reverse
    hi TabLine guifg=#f0f0f0 guibg=#00998c gui=NONE cterm=NONE
    hi TabLineFill guifg=#fafafa guibg=#00998c gui=NONE cterm=NONE
    hi TabLineSel guifg=#fafafa guibg=#00998c gui=bold cterm=bold
    hi VertSplit guifg=#f0f0f0 guibg=#00998c gui=NONE cterm=NONE
    hi WildMenu guifg=#fafafa guibg=#db2d45 gui=bold cterm=bold
  elseif s:fc == 3
    hi StatusLine guifg=#d87900 guibg=#fafafa gui=bold,reverse cterm=bold,reverse
    hi StatusLineNC guifg=#d87900 guibg=#f0f0f0 gui=reverse cterm=reverse
    hi TabLine guifg=#f0f0f0 guibg=#d87900 gui=NONE cterm=NONE
    hi TabLineFill guifg=#fafafa guibg=#d87900 gui=NONE cterm=NONE
    hi TabLineSel guifg=#fafafa guibg=#d87900 gui=bold cterm=bold
    hi VertSplit guifg=#f0f0f0 guibg=#d87900 gui=NONE cterm=NONE
    hi WildMenu guifg=#fafafa guibg=#db2d45 gui=bold cterm=bold
  elseif s:fc == 4
    hi StatusLine guifg=#527f8f guibg=#fafafa gui=bold,reverse cterm=bold,reverse
    hi StatusLineNC guifg=#527f8f guibg=#f0f0f0 gui=reverse cterm=reverse
    hi TabLine guifg=#fafafa guibg=#527f8f gui=NONE cterm=NONE
    hi TabLineFill guifg=#fafafa guibg=#527f8f gui=NONE cterm=NONE
    hi TabLineSel guifg=#fafafa guibg=#527f8f gui=bold cterm=bold
    hi VertSplit guifg=#f0f0f0 guibg=#527f8f gui=NONE cterm=NONE
    hi WildMenu guifg=#fafafa guibg=#db2d45 gui=bold cterm=bold
  elseif s:fc == 5
    hi StatusLine guifg=#db2d45 guibg=#fafafa gui=bold,reverse cterm=bold,reverse
    hi StatusLineNC guifg=#db2d45 guibg=#f0f0f0 gui=reverse cterm=reverse
    hi TabLine guifg=#f0f0f0 guibg=#db2d45 gui=NONE cterm=NONE
    hi TabLineFill guifg=#f0f0f0 guibg=#db2d45 gui=NONE cterm=NONE
    hi TabLineSel guifg=#fafafa guibg=#db2d45 gui=bold cterm=bold
    hi VertSplit guifg=#f0f0f0 guibg=#db2d45 gui=NONE cterm=NONE
    hi WildMenu guifg=#fafafa guibg=#d87900 gui=NONE cterm=NONE
  elseif s:fc == 6
    hi StatusLine guifg=#159ccc guibg=#fafafa gui=bold,reverse cterm=bold,reverse
    hi StatusLineNC guifg=#159ccc guibg=#f0f0f0 gui=reverse cterm=reverse
    hi TabLine guifg=#f0f0f0 guibg=#159ccc gui=NONE cterm=NONE
    hi TabLineFill guifg=#fafafa guibg=#159ccc gui=NONE cterm=NONE
    hi TabLineSel guifg=#fafafa guibg=#159ccc gui=bold cterm=bold
    hi VertSplit guifg=#f0f0f0 guibg=#159ccc gui=NONE cterm=NONE
    hi WildMenu guifg=#fafafa guibg=#db2d45 gui=bold cterm=bold
  elseif s:fc == 7
    hi StatusLine guifg=#f0f0f0 guibg=#5f5f61 gui=bold,reverse cterm=bold,reverse
    hi StatusLineNC guifg=#f0f0f0 guibg=#888888 gui=reverse cterm=reverse
    hi TabLine guifg=#888888 guibg=#f0f0f0 gui=NONE cterm=NONE
    hi TabLineFill guifg=#5f5f61 guibg=#f0f0f0 gui=NONE cterm=NONE
    hi TabLineSel guifg=#5f5f61 guibg=#f0f0f0 gui=bold cterm=bold
    hi VertSplit guifg=#888888 guibg=#f0f0f0 gui=NONE cterm=NONE
    hi WildMenu guifg=#fafafa guibg=#db2d45 gui=bold cterm=bold
  elseif s:fc == 8
    hi StatusLine guifg=#888888 guibg=#fafafa gui=bold,reverse cterm=bold,reverse
    hi StatusLineNC guifg=#888888 guibg=#f0f0f0 gui=reverse cterm=reverse
    hi TabLine guifg=#f0f0f0 guibg=#888888 gui=NONE cterm=NONE
    hi TabLineFill guifg=#fafafa guibg=#888888 gui=NONE cterm=NONE
    hi TabLineSel guifg=#fafafa guibg=#888888 gui=bold cterm=bold
    hi VertSplit guifg=#f0f0f0 guibg=#888888 gui=NONE cterm=NONE
    hi WildMenu guifg=#fafafa guibg=#db2d45 gui=bold cterm=bold
  elseif s:fc == 9
    hi StatusLine guifg=#d87900 guibg=#fafafa gui=bold,reverse cterm=bold,reverse
    hi StatusLineNC guifg=#d87900 guibg=#f0f0f0 gui=reverse cterm=reverse
    hi TabLine guifg=#f0f0f0 guibg=#d87900 gui=NONE cterm=NONE
    hi TabLineFill guifg=#fafafa guibg=#d87900 gui=NONE cterm=NONE
    hi TabLineSel guifg=#fafafa guibg=#d87900 gui=bold cterm=bold
    hi VertSplit guifg=#f0f0f0 guibg=#d87900 gui=NONE cterm=NONE
    hi WildMenu guifg=#fafafa guibg=#abb96e gui=bold cterm=bold
  elseif s:fc == 10
    hi StatusLine guifg=#abb96e guibg=#fafafa gui=bold,reverse cterm=bold,reverse
    hi StatusLineNC guifg=#abb96e guibg=#f0f0f0 gui=reverse cterm=reverse
    hi TabLine guifg=#f0f0f0 guibg=#abb96e gui=NONE cterm=NONE
    hi TabLineFill guifg=#fafafa guibg=#abb96e gui=NONE cterm=NONE
    hi TabLineSel guifg=#fafafa guibg=#abb96e gui=bold cterm=bold
    hi VertSplit guifg=#f0f0f0 guibg=#abb96e gui=NONE cterm=NONE
    hi WildMenu guifg=#fafafa guibg=#db2d45 gui=bold cterm=bold
  elseif s:fc == 11
    hi StatusLine guifg=#e1ad0b guibg=#fafafa gui=bold,reverse cterm=bold,reverse
    hi StatusLineNC guifg=#e1ad0b guibg=#f0f0f0 gui=reverse cterm=reverse
    hi TabLine guifg=#f0f0f0 guibg=#e1ad0b gui=NONE cterm=NONE
    hi TabLineFill guifg=#fafafa guibg=#e1ad0b gui=NONE cterm=NONE
    hi TabLineSel guifg=#fafafa guibg=#e1ad0b gui=bold cterm=bold
    hi VertSplit guifg=#f0f0f0 guibg=#e1ad0b gui=NONE cterm=NONE
    hi WildMenu guifg=#fafafa guibg=#db2d45 gui=bold cterm=bold
  elseif s:fc == 12
    hi StatusLine guifg=#8c61a6 guibg=#fafafa gui=bold,reverse cterm=bold,reverse
    hi StatusLineNC guifg=#8c61a6 guibg=#f0f0f0 gui=reverse cterm=reverse
    hi TabLine guifg=#f0f0f0 guibg=#8c61a6 gui=NONE cterm=NONE
    hi TabLineFill guifg=#fafafa guibg=#8c61a6 gui=NONE cterm=NONE
    hi TabLineSel guifg=#fafafa guibg=#8c61a6 gui=bold cterm=bold
    hi VertSplit guifg=#f0f0f0 guibg=#8c61a6 gui=NONE cterm=NONE
    hi WildMenu guifg=#fafafa guibg=#db2d45 gui=bold cterm=bold
  elseif s:fc == 13
    hi StatusLine guifg=#eb314b guibg=#fafafa gui=bold,reverse cterm=bold,reverse
    hi StatusLineNC guifg=#eb314b guibg=#f0f0f0 gui=reverse cterm=reverse
    hi TabLine guifg=#f0f0f0 guibg=#eb314b gui=NONE cterm=NONE
    hi TabLineFill guifg=#f0f0f0 guibg=#eb314b gui=NONE cterm=NONE
    hi TabLineSel guifg=#fafafa guibg=#eb314b gui=bold cterm=bold
    hi VertSplit guifg=#f0f0f0 guibg=#eb314b gui=NONE cterm=NONE
    hi WildMenu guifg=#fafafa guibg=#d87900 gui=NONE cterm=NONE
  elseif s:fc == 14
    hi StatusLine guifg=#23bce1 guibg=#fafafa gui=bold,reverse cterm=bold,reverse
    hi StatusLineNC guifg=#23bce1 guibg=#f0f0f0 gui=reverse cterm=reverse
    hi TabLine guifg=#f0f0f0 guibg=#23bce1 gui=NONE cterm=NONE
    hi TabLineFill guifg=#fafafa guibg=#23bce1 gui=NONE cterm=NONE
    hi TabLineSel guifg=#fafafa guibg=#23bce1 gui=bold cterm=bold
    hi VertSplit guifg=#f0f0f0 guibg=#23bce1 gui=NONE cterm=NONE
    hi WildMenu guifg=#fafafa guibg=#db2d45 gui=bold cterm=bold
  elseif s:fc == 15
    hi StatusLine guifg=#fafafa guibg=#5f5f61 gui=bold,reverse cterm=bold,reverse
    hi StatusLineNC guifg=#fafafa guibg=#888888 gui=reverse cterm=reverse
    hi TabLine guifg=#888888 guibg=#fafafa gui=NONE cterm=NONE
    hi TabLineFill guifg=#888888 guibg=#fafafa gui=NONE cterm=NONE
    hi TabLineSel guifg=#5f5f61 guibg=#fafafa gui=bold cterm=bold
    hi VertSplit guifg=#888888 guibg=#fafafa gui=NONE cterm=NONE
    hi WildMenu guifg=#fafafa guibg=#888888 gui=NONE cterm=NONE
  endif
  unlet s:fc
  hi Boolean guifg=#abb96e guibg=NONE gui=NONE cterm=NONE
  hi Character guifg=#db2d45 guibg=NONE gui=NONE cterm=NONE
  hi Comment guifg=#888888 guibg=NONE gui=italic cterm=italic
  hi Constant guifg=#00998c guibg=NONE gui=NONE cterm=NONE
  hi Debug guifg=#db2d45 guibg=NONE gui=NONE cterm=NONE
  hi Delimiter guifg=#527f8f guibg=NONE gui=NONE cterm=NONE
  hi Error guifg=#e8503f guibg=#fafafa gui=reverse cterm=reverse
  hi Float guifg=#abb96e guibg=NONE gui=NONE cterm=NONE
  hi Function guifg=#00998c guibg=NONE gui=NONE cterm=NONE
  hi Identifier guifg=#527f8f guibg=NONE gui=NONE cterm=NONE
  hi Ignore guifg=#d87900 guibg=NONE gui=NONE cterm=NONE
  hi Include guifg=#8c61a6 guibg=NONE gui=NONE cterm=NONE
  hi Keyword guifg=#159ccc guibg=NONE gui=NONE cterm=NONE
  hi Label guifg=#00998c guibg=NONE gui=NONE cterm=NONE
  hi Number guifg=#00998c guibg=NONE gui=NONE cterm=NONE
  hi Operator guifg=#159ccc guibg=NONE gui=NONE cterm=NONE
  hi PreProc guifg=#e8503f guibg=NONE gui=NONE cterm=NONE
  hi Special guifg=#e8503f guibg=NONE gui=NONE cterm=NONE
  hi SpecialChar guifg=#db2d45 guibg=NONE gui=NONE cterm=NONE
  hi SpecialComment guifg=#db2d45 guibg=NONE gui=NONE cterm=NONE
  hi Statement guifg=#159ccc guibg=NONE gui=NONE cterm=NONE
  hi StorageClass guifg=#159ccc guibg=NONE gui=NONE cterm=NONE
  hi String guifg=#d87900 guibg=NONE gui=NONE cterm=NONE
  hi Structure guifg=#e8503f guibg=NONE gui=NONE cterm=NONE
  hi Todo guifg=#db2d45 guibg=NONE gui=bold cterm=bold
  hi Type guifg=#8c61a6 guibg=NONE gui=NONE cterm=NONE
  hi Underlined guifg=NONE guibg=NONE gui=underline ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM guifg=NONE guibg=#fafafa gui=NONE cterm=NONE
  hi ToolbarLine guifg=#888888 guibg=#f0f0f0 gui=NONE cterm=NONE
  hi ToolbarButton guifg=#5f5f61 guibg=#f0f0f0 gui=bold cterm=bold
  hi NormalMode guifg=#888888 guibg=#fafafa gui=reverse cterm=reverse
  hi InsertMode guifg=#abb96e guibg=#fafafa gui=reverse cterm=reverse
  hi ReplaceMode guifg=#d87900 guibg=#fafafa gui=reverse cterm=reverse
  hi VisualMode guifg=#527f8f guibg=#fafafa gui=reverse cterm=reverse
  hi CommandMode guifg=#db2d45 guibg=#fafafa gui=reverse cterm=reverse
  if !s:italics
    hi Comment gui=NONE cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC guifg=#fafafa guibg=#5f5f61 gui=NONE cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 256
  if get(g:, 'wwdc17_transp_bg', 0)
    hi Normal ctermfg=59 ctermbg=NONE cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=NONE cterm=underline
    hi CursorLineNr ctermfg=172 ctermbg=NONE cterm=NONE
    hi Folded ctermfg=102 ctermbg=NONE cterm=italic
    hi LineNr ctermfg=102 ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=102 ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=59 ctermbg=NONE cterm=NONE
    if !s:italics
      hi Folded cterm=NONE
    endif
  else
    hi Normal ctermfg=59 ctermbg=231 cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=255 cterm=NONE
    hi CursorLineNr ctermfg=172 ctermbg=255 cterm=NONE
    hi Folded ctermfg=102 ctermbg=255 cterm=italic
    hi LineNr ctermfg=102 ctermbg=255 cterm=NONE
    hi FoldColumn ctermfg=102 ctermbg=255 cterm=NONE
    hi Terminal ctermfg=59 ctermbg=231 cterm=NONE
    if !s:italics
      hi Folded cterm=NONE
    endif
  endif
  hi ColorColumn ctermfg=NONE ctermbg=255 cterm=NONE
  hi Conceal ctermfg=30 ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=255 cterm=NONE
  hi DiffAdd ctermfg=143 ctermbg=59 cterm=reverse
  hi DiffChange ctermfg=172 ctermbg=231 cterm=reverse
  hi DiffDelete ctermfg=167 ctermbg=231 cterm=reverse
  hi DiffText ctermfg=74 ctermbg=231 cterm=bold,reverse
  hi Directory ctermfg=30 ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=172 ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=167 ctermbg=231 cterm=reverse
  hi IncSearch ctermfg=172 ctermbg=231 cterm=reverse
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi ModeMsg ctermfg=59 ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=172 ctermbg=NONE cterm=NONE
  hi NonText ctermfg=102 ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=59 ctermbg=255 cterm=NONE
  hi PmenuSbar ctermfg=172 ctermbg=102 cterm=NONE
  hi PmenuSel ctermfg=231 ctermbg=172 cterm=NONE
  hi PmenuThumb ctermfg=167 ctermbg=172 cterm=NONE
  hi Question ctermfg=59 ctermbg=NONE cterm=NONE
  hi Search ctermfg=178 ctermbg=231 cterm=reverse
  hi SignColumn ctermfg=172 ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=172 ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=197 ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=197 ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=197 ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=197 ctermbg=NONE cterm=underline
  hi Title ctermfg=172 ctermbg=NONE cterm=bold
  hi Visual ctermfg=66 ctermbg=231 cterm=reverse
  hi VisualNOS ctermfg=231 ctermbg=66 cterm=NONE
  hi WarningMsg ctermfg=167 ctermbg=NONE cterm=NONE
  let s:fc = abs(get(g:, 'wwdc17_frame_color', 10)) % 16
  if s:fc == 0
    hi StatusLine ctermfg=59 ctermbg=231 cterm=bold,reverse
    hi StatusLineNC ctermfg=59 ctermbg=255 cterm=reverse
    hi TabLine ctermfg=255 ctermbg=59 cterm=NONE
    hi TabLineFill ctermfg=231 ctermbg=59 cterm=NONE
    hi TabLineSel ctermfg=231 ctermbg=59 cterm=bold
    hi VertSplit ctermfg=255 ctermbg=59 cterm=NONE
    hi WildMenu ctermfg=231 ctermbg=197 cterm=bold
  elseif s:fc == 1
    hi StatusLine ctermfg=167 ctermbg=231 cterm=bold,reverse
    hi StatusLineNC ctermfg=167 ctermbg=255 cterm=reverse
    hi TabLine ctermfg=255 ctermbg=167 cterm=NONE
    hi TabLineFill ctermfg=231 ctermbg=167 cterm=NONE
    hi TabLineSel ctermfg=231 ctermbg=172 cterm=bold
    hi VertSplit ctermfg=255 ctermbg=167 cterm=NONE
    hi WildMenu ctermfg=231 ctermbg=143 cterm=bold
  elseif s:fc == 2
    hi StatusLine ctermfg=30 ctermbg=231 cterm=bold,reverse
    hi StatusLineNC ctermfg=30 ctermbg=255 cterm=reverse
    hi TabLine ctermfg=255 ctermbg=30 cterm=NONE
    hi TabLineFill ctermfg=231 ctermbg=30 cterm=NONE
    hi TabLineSel ctermfg=231 ctermbg=30 cterm=bold
    hi VertSplit ctermfg=255 ctermbg=30 cterm=NONE
    hi WildMenu ctermfg=231 ctermbg=197 cterm=bold
  elseif s:fc == 3
    hi StatusLine ctermfg=172 ctermbg=231 cterm=bold,reverse
    hi StatusLineNC ctermfg=172 ctermbg=255 cterm=reverse
    hi TabLine ctermfg=255 ctermbg=172 cterm=NONE
    hi TabLineFill ctermfg=231 ctermbg=172 cterm=NONE
    hi TabLineSel ctermfg=231 ctermbg=172 cterm=bold
    hi VertSplit ctermfg=255 ctermbg=172 cterm=NONE
    hi WildMenu ctermfg=231 ctermbg=197 cterm=bold
  elseif s:fc == 4
    hi StatusLine ctermfg=66 ctermbg=231 cterm=bold,reverse
    hi StatusLineNC ctermfg=66 ctermbg=255 cterm=reverse
    hi TabLine ctermfg=231 ctermbg=66 cterm=NONE
    hi TabLineFill ctermfg=231 ctermbg=66 cterm=NONE
    hi TabLineSel ctermfg=231 ctermbg=66 cterm=bold
    hi VertSplit ctermfg=255 ctermbg=66 cterm=NONE
    hi WildMenu ctermfg=231 ctermbg=197 cterm=bold
  elseif s:fc == 5
    hi StatusLine ctermfg=197 ctermbg=231 cterm=bold,reverse
    hi StatusLineNC ctermfg=197 ctermbg=255 cterm=reverse
    hi TabLine ctermfg=255 ctermbg=197 cterm=NONE
    hi TabLineFill ctermfg=255 ctermbg=197 cterm=NONE
    hi TabLineSel ctermfg=231 ctermbg=197 cterm=bold
    hi VertSplit ctermfg=255 ctermbg=197 cterm=NONE
    hi WildMenu ctermfg=231 ctermbg=172 cterm=NONE
  elseif s:fc == 6
    hi StatusLine ctermfg=74 ctermbg=231 cterm=bold,reverse
    hi StatusLineNC ctermfg=74 ctermbg=255 cterm=reverse
    hi TabLine ctermfg=255 ctermbg=74 cterm=NONE
    hi TabLineFill ctermfg=231 ctermbg=74 cterm=NONE
    hi TabLineSel ctermfg=231 ctermbg=74 cterm=bold
    hi VertSplit ctermfg=255 ctermbg=74 cterm=NONE
    hi WildMenu ctermfg=231 ctermbg=197 cterm=bold
  elseif s:fc == 7
    hi StatusLine ctermfg=255 ctermbg=59 cterm=bold,reverse
    hi StatusLineNC ctermfg=255 ctermbg=102 cterm=reverse
    hi TabLine ctermfg=102 ctermbg=255 cterm=NONE
    hi TabLineFill ctermfg=59 ctermbg=255 cterm=NONE
    hi TabLineSel ctermfg=59 ctermbg=255 cterm=bold
    hi VertSplit ctermfg=102 ctermbg=255 cterm=NONE
    hi WildMenu ctermfg=231 ctermbg=197 cterm=bold
  elseif s:fc == 8
    hi StatusLine ctermfg=102 ctermbg=231 cterm=bold,reverse
    hi StatusLineNC ctermfg=102 ctermbg=255 cterm=reverse
    hi TabLine ctermfg=255 ctermbg=102 cterm=NONE
    hi TabLineFill ctermfg=231 ctermbg=102 cterm=NONE
    hi TabLineSel ctermfg=231 ctermbg=102 cterm=bold
    hi VertSplit ctermfg=255 ctermbg=102 cterm=NONE
    hi WildMenu ctermfg=231 ctermbg=197 cterm=bold
  elseif s:fc == 9
    hi StatusLine ctermfg=172 ctermbg=231 cterm=bold,reverse
    hi StatusLineNC ctermfg=172 ctermbg=255 cterm=reverse
    hi TabLine ctermfg=255 ctermbg=172 cterm=NONE
    hi TabLineFill ctermfg=231 ctermbg=172 cterm=NONE
    hi TabLineSel ctermfg=231 ctermbg=172 cterm=bold
    hi VertSplit ctermfg=255 ctermbg=172 cterm=NONE
    hi WildMenu ctermfg=231 ctermbg=143 cterm=bold
  elseif s:fc == 10
    hi StatusLine ctermfg=143 ctermbg=231 cterm=bold,reverse
    hi StatusLineNC ctermfg=143 ctermbg=255 cterm=reverse
    hi TabLine ctermfg=255 ctermbg=143 cterm=NONE
    hi TabLineFill ctermfg=231 ctermbg=143 cterm=NONE
    hi TabLineSel ctermfg=231 ctermbg=143 cterm=bold
    hi VertSplit ctermfg=255 ctermbg=143 cterm=NONE
    hi WildMenu ctermfg=231 ctermbg=197 cterm=bold
  elseif s:fc == 11
    hi StatusLine ctermfg=178 ctermbg=231 cterm=bold,reverse
    hi StatusLineNC ctermfg=178 ctermbg=255 cterm=reverse
    hi TabLine ctermfg=255 ctermbg=178 cterm=NONE
    hi TabLineFill ctermfg=231 ctermbg=178 cterm=NONE
    hi TabLineSel ctermfg=231 ctermbg=178 cterm=bold
    hi VertSplit ctermfg=255 ctermbg=178 cterm=NONE
    hi WildMenu ctermfg=231 ctermbg=197 cterm=bold
  elseif s:fc == 12
    hi StatusLine ctermfg=97 ctermbg=231 cterm=bold,reverse
    hi StatusLineNC ctermfg=97 ctermbg=255 cterm=reverse
    hi TabLine ctermfg=255 ctermbg=97 cterm=NONE
    hi TabLineFill ctermfg=231 ctermbg=97 cterm=NONE
    hi TabLineSel ctermfg=231 ctermbg=97 cterm=bold
    hi VertSplit ctermfg=255 ctermbg=97 cterm=NONE
    hi WildMenu ctermfg=231 ctermbg=197 cterm=bold
  elseif s:fc == 13
    hi StatusLine ctermfg=197 ctermbg=231 cterm=bold,reverse
    hi StatusLineNC ctermfg=197 ctermbg=255 cterm=reverse
    hi TabLine ctermfg=255 ctermbg=197 cterm=NONE
    hi TabLineFill ctermfg=255 ctermbg=197 cterm=NONE
    hi TabLineSel ctermfg=231 ctermbg=197 cterm=bold
    hi VertSplit ctermfg=255 ctermbg=197 cterm=NONE
    hi WildMenu ctermfg=231 ctermbg=172 cterm=NONE
  elseif s:fc == 14
    hi StatusLine ctermfg=38 ctermbg=231 cterm=bold,reverse
    hi StatusLineNC ctermfg=38 ctermbg=255 cterm=reverse
    hi TabLine ctermfg=255 ctermbg=38 cterm=NONE
    hi TabLineFill ctermfg=231 ctermbg=38 cterm=NONE
    hi TabLineSel ctermfg=231 ctermbg=38 cterm=bold
    hi VertSplit ctermfg=255 ctermbg=38 cterm=NONE
    hi WildMenu ctermfg=231 ctermbg=197 cterm=bold
  elseif s:fc == 15
    hi StatusLine ctermfg=231 ctermbg=59 cterm=bold,reverse
    hi StatusLineNC ctermfg=231 ctermbg=102 cterm=reverse
    hi TabLine ctermfg=102 ctermbg=231 cterm=NONE
    hi TabLineFill ctermfg=102 ctermbg=231 cterm=NONE
    hi TabLineSel ctermfg=59 ctermbg=231 cterm=bold
    hi VertSplit ctermfg=102 ctermbg=231 cterm=NONE
    hi WildMenu ctermfg=231 ctermbg=102 cterm=NONE
  endif
  unlet s:fc
  hi Boolean ctermfg=143 ctermbg=NONE cterm=NONE
  hi Character ctermfg=197 ctermbg=NONE cterm=NONE
  hi Comment ctermfg=102 ctermbg=NONE cterm=italic
  hi Constant ctermfg=30 ctermbg=NONE cterm=NONE
  hi Debug ctermfg=197 ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=66 ctermbg=NONE cterm=NONE
  hi Error ctermfg=167 ctermbg=231 cterm=reverse
  hi Float ctermfg=143 ctermbg=NONE cterm=NONE
  hi Function ctermfg=30 ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=66 ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=172 ctermbg=NONE cterm=NONE
  hi Include ctermfg=97 ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=74 ctermbg=NONE cterm=NONE
  hi Label ctermfg=30 ctermbg=NONE cterm=NONE
  hi Number ctermfg=30 ctermbg=NONE cterm=NONE
  hi Operator ctermfg=74 ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=167 ctermbg=NONE cterm=NONE
  hi Special ctermfg=167 ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=197 ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=197 ctermbg=NONE cterm=NONE
  hi Statement ctermfg=74 ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=74 ctermbg=NONE cterm=NONE
  hi String ctermfg=172 ctermbg=NONE cterm=NONE
  hi Structure ctermfg=167 ctermbg=NONE cterm=NONE
  hi Todo ctermfg=197 ctermbg=NONE cterm=bold
  hi Type ctermfg=97 ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=231 cterm=NONE
  hi ToolbarLine ctermfg=102 ctermbg=255 cterm=NONE
  hi ToolbarButton ctermfg=59 ctermbg=255 cterm=bold
  hi NormalMode ctermfg=102 ctermbg=231 cterm=reverse
  hi InsertMode ctermfg=143 ctermbg=231 cterm=reverse
  hi ReplaceMode ctermfg=172 ctermbg=231 cterm=reverse
  hi VisualMode ctermfg=66 ctermbg=231 cterm=reverse
  hi CommandMode ctermfg=197 ctermbg=231 cterm=reverse
  if !s:italics
    hi Comment cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC ctermfg=231 ctermbg=59 cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 8
  if get(g:, 'wwdc17_transp_bg', 0)
    hi Normal ctermfg=Black ctermbg=NONE cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=NONE cterm=underline
    hi CursorLineNr ctermfg=Red ctermbg=NONE cterm=NONE
    hi Folded ctermfg=DarkGray ctermbg=NONE cterm=italic
    hi LineNr ctermfg=DarkGray ctermbg=NONE cterm=NONE
    hi FoldColumn ctermfg=DarkGray ctermbg=NONE cterm=NONE
    hi Terminal ctermfg=Black ctermbg=NONE cterm=NONE
    if !s:italics
      hi Folded cterm=NONE
    endif
  else
    hi Normal ctermfg=Black ctermbg=White cterm=NONE
    hi CursorLine ctermfg=NONE ctermbg=Gray cterm=NONE
    hi CursorLineNr ctermfg=Red ctermbg=Gray cterm=NONE
    hi Folded ctermfg=DarkGray ctermbg=Gray cterm=italic
    hi LineNr ctermfg=DarkGray ctermbg=Gray cterm=NONE
    hi FoldColumn ctermfg=DarkGray ctermbg=Gray cterm=NONE
    hi Terminal ctermfg=Black ctermbg=White cterm=NONE
    if !s:italics
      hi Folded cterm=NONE
    endif
  endif
  hi ColorColumn ctermfg=NONE ctermbg=Gray cterm=NONE
  hi Conceal ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Cursor ctermfg=NONE ctermbg=NONE cterm=reverse
  hi CursorColumn ctermfg=NONE ctermbg=Gray cterm=NONE
  hi DiffAdd ctermfg=Green ctermbg=Black cterm=reverse
  hi DiffChange ctermfg=DarkYellow ctermbg=White cterm=reverse
  hi DiffDelete ctermfg=DarkRed ctermbg=White cterm=reverse
  hi DiffText ctermfg=DarkCyan ctermbg=White cterm=bold,reverse
  hi Directory ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi EndOfBuffer ctermfg=Red ctermbg=NONE cterm=NONE
  hi ErrorMsg ctermfg=DarkRed ctermbg=White cterm=reverse
  hi IncSearch ctermfg=Red ctermbg=White cterm=reverse
  hi MatchParen ctermfg=NONE ctermbg=NONE cterm=bold,underline
  hi ModeMsg ctermfg=Black ctermbg=NONE cterm=NONE
  hi MoreMsg ctermfg=Red ctermbg=NONE cterm=NONE
  hi NonText ctermfg=DarkGray ctermbg=NONE cterm=NONE
  hi Pmenu ctermfg=Black ctermbg=Gray cterm=NONE
  hi PmenuSbar ctermfg=Red ctermbg=DarkGray cterm=NONE
  hi PmenuSel ctermfg=White ctermbg=Red cterm=NONE
  hi PmenuThumb ctermfg=DarkRed ctermbg=Red cterm=NONE
  hi Question ctermfg=Black ctermbg=NONE cterm=NONE
  hi Search ctermfg=Yellow ctermbg=White cterm=reverse
  hi SignColumn ctermfg=Red ctermbg=NONE cterm=NONE
  hi SpecialKey ctermfg=Red ctermbg=NONE cterm=NONE
  hi SpellBad ctermfg=DarkMagenta ctermbg=NONE cterm=underline
  hi SpellCap ctermfg=DarkMagenta ctermbg=NONE cterm=underline
  hi SpellLocal ctermfg=DarkMagenta ctermbg=NONE cterm=underline
  hi SpellRare ctermfg=DarkMagenta ctermbg=NONE cterm=underline
  hi Title ctermfg=Red ctermbg=NONE cterm=bold
  hi Visual ctermfg=DarkBlue ctermbg=White cterm=reverse
  hi VisualNOS ctermfg=White ctermbg=DarkBlue cterm=NONE
  hi WarningMsg ctermfg=DarkRed ctermbg=NONE cterm=NONE
  let s:fc = abs(get(g:, 'wwdc17_frame_color', 10)) % 16
  if s:fc == 0
    hi StatusLine ctermfg=Black ctermbg=White cterm=bold,reverse
    hi StatusLineNC ctermfg=Black ctermbg=Gray cterm=reverse
    hi TabLine ctermfg=Gray ctermbg=Black cterm=NONE
    hi TabLineFill ctermfg=White ctermbg=Black cterm=NONE
    hi TabLineSel ctermfg=White ctermbg=Black cterm=bold
    hi VertSplit ctermfg=Gray ctermbg=Black cterm=NONE
    hi WildMenu ctermfg=White ctermbg=DarkMagenta cterm=bold
  elseif s:fc == 1
    hi StatusLine ctermfg=DarkRed ctermbg=White cterm=bold,reverse
    hi StatusLineNC ctermfg=DarkRed ctermbg=Gray cterm=reverse
    hi TabLine ctermfg=Gray ctermbg=DarkRed cterm=NONE
    hi TabLineFill ctermfg=White ctermbg=DarkRed cterm=NONE
    hi TabLineSel ctermfg=White ctermbg=Red cterm=bold
    hi VertSplit ctermfg=Gray ctermbg=DarkRed cterm=NONE
    hi WildMenu ctermfg=White ctermbg=Green cterm=bold
  elseif s:fc == 2
    hi StatusLine ctermfg=DarkGreen ctermbg=White cterm=bold,reverse
    hi StatusLineNC ctermfg=DarkGreen ctermbg=Gray cterm=reverse
    hi TabLine ctermfg=Gray ctermbg=DarkGreen cterm=NONE
    hi TabLineFill ctermfg=White ctermbg=DarkGreen cterm=NONE
    hi TabLineSel ctermfg=White ctermbg=DarkGreen cterm=bold
    hi VertSplit ctermfg=Gray ctermbg=DarkGreen cterm=NONE
    hi WildMenu ctermfg=White ctermbg=DarkMagenta cterm=bold
  elseif s:fc == 3
    hi StatusLine ctermfg=DarkYellow ctermbg=White cterm=bold,reverse
    hi StatusLineNC ctermfg=DarkYellow ctermbg=Gray cterm=reverse
    hi TabLine ctermfg=Gray ctermbg=DarkYellow cterm=NONE
    hi TabLineFill ctermfg=White ctermbg=DarkYellow cterm=NONE
    hi TabLineSel ctermfg=White ctermbg=DarkYellow cterm=bold
    hi VertSplit ctermfg=Gray ctermbg=DarkYellow cterm=NONE
    hi WildMenu ctermfg=White ctermbg=DarkMagenta cterm=bold
  elseif s:fc == 4
    hi StatusLine ctermfg=DarkBlue ctermbg=White cterm=bold,reverse
    hi StatusLineNC ctermfg=DarkBlue ctermbg=Gray cterm=reverse
    hi TabLine ctermfg=White ctermbg=DarkBlue cterm=NONE
    hi TabLineFill ctermfg=White ctermbg=DarkBlue cterm=NONE
    hi TabLineSel ctermfg=White ctermbg=DarkBlue cterm=bold
    hi VertSplit ctermfg=Gray ctermbg=DarkBlue cterm=NONE
    hi WildMenu ctermfg=White ctermbg=DarkMagenta cterm=bold
  elseif s:fc == 5
    hi StatusLine ctermfg=DarkMagenta ctermbg=White cterm=bold,reverse
    hi StatusLineNC ctermfg=DarkMagenta ctermbg=Gray cterm=reverse
    hi TabLine ctermfg=Gray ctermbg=DarkMagenta cterm=NONE
    hi TabLineFill ctermfg=Gray ctermbg=DarkMagenta cterm=NONE
    hi TabLineSel ctermfg=White ctermbg=DarkMagenta cterm=bold
    hi VertSplit ctermfg=Gray ctermbg=DarkMagenta cterm=NONE
    hi WildMenu ctermfg=White ctermbg=DarkYellow cterm=NONE
  elseif s:fc == 6
    hi StatusLine ctermfg=DarkCyan ctermbg=White cterm=bold,reverse
    hi StatusLineNC ctermfg=DarkCyan ctermbg=Gray cterm=reverse
    hi TabLine ctermfg=Gray ctermbg=DarkCyan cterm=NONE
    hi TabLineFill ctermfg=White ctermbg=DarkCyan cterm=NONE
    hi TabLineSel ctermfg=White ctermbg=DarkCyan cterm=bold
    hi VertSplit ctermfg=Gray ctermbg=DarkCyan cterm=NONE
    hi WildMenu ctermfg=White ctermbg=DarkMagenta cterm=bold
  elseif s:fc == 7
    hi StatusLine ctermfg=Gray ctermbg=Black cterm=bold,reverse
    hi StatusLineNC ctermfg=Gray ctermbg=DarkGray cterm=reverse
    hi TabLine ctermfg=DarkGray ctermbg=Gray cterm=NONE
    hi TabLineFill ctermfg=Black ctermbg=Gray cterm=NONE
    hi TabLineSel ctermfg=Black ctermbg=Gray cterm=bold
    hi VertSplit ctermfg=DarkGray ctermbg=Gray cterm=NONE
    hi WildMenu ctermfg=White ctermbg=DarkMagenta cterm=bold
  elseif s:fc == 8
    hi StatusLine ctermfg=DarkGray ctermbg=White cterm=bold,reverse
    hi StatusLineNC ctermfg=DarkGray ctermbg=Gray cterm=reverse
    hi TabLine ctermfg=Gray ctermbg=DarkGray cterm=NONE
    hi TabLineFill ctermfg=White ctermbg=DarkGray cterm=NONE
    hi TabLineSel ctermfg=White ctermbg=DarkGray cterm=bold
    hi VertSplit ctermfg=Gray ctermbg=DarkGray cterm=NONE
    hi WildMenu ctermfg=White ctermbg=DarkMagenta cterm=bold
  elseif s:fc == 9
    hi StatusLine ctermfg=Red ctermbg=White cterm=bold,reverse
    hi StatusLineNC ctermfg=Red ctermbg=Gray cterm=reverse
    hi TabLine ctermfg=Gray ctermbg=Red cterm=NONE
    hi TabLineFill ctermfg=White ctermbg=Red cterm=NONE
    hi TabLineSel ctermfg=White ctermbg=Red cterm=bold
    hi VertSplit ctermfg=Gray ctermbg=Red cterm=NONE
    hi WildMenu ctermfg=White ctermbg=Green cterm=bold
  elseif s:fc == 10
    hi StatusLine ctermfg=Green ctermbg=White cterm=bold,reverse
    hi StatusLineNC ctermfg=Green ctermbg=Gray cterm=reverse
    hi TabLine ctermfg=Gray ctermbg=Green cterm=NONE
    hi TabLineFill ctermfg=White ctermbg=Green cterm=NONE
    hi TabLineSel ctermfg=White ctermbg=Green cterm=bold
    hi VertSplit ctermfg=Gray ctermbg=Green cterm=NONE
    hi WildMenu ctermfg=White ctermbg=DarkMagenta cterm=bold
  elseif s:fc == 11
    hi StatusLine ctermfg=Yellow ctermbg=White cterm=bold,reverse
    hi StatusLineNC ctermfg=Yellow ctermbg=Gray cterm=reverse
    hi TabLine ctermfg=Gray ctermbg=Yellow cterm=NONE
    hi TabLineFill ctermfg=White ctermbg=Yellow cterm=NONE
    hi TabLineSel ctermfg=White ctermbg=Yellow cterm=bold
    hi VertSplit ctermfg=Gray ctermbg=Yellow cterm=NONE
    hi WildMenu ctermfg=White ctermbg=DarkMagenta cterm=bold
  elseif s:fc == 12
    hi StatusLine ctermfg=Blue ctermbg=White cterm=bold,reverse
    hi StatusLineNC ctermfg=Blue ctermbg=Gray cterm=reverse
    hi TabLine ctermfg=Gray ctermbg=Blue cterm=NONE
    hi TabLineFill ctermfg=White ctermbg=Blue cterm=NONE
    hi TabLineSel ctermfg=White ctermbg=Blue cterm=bold
    hi VertSplit ctermfg=Gray ctermbg=Blue cterm=NONE
    hi WildMenu ctermfg=White ctermbg=DarkMagenta cterm=bold
  elseif s:fc == 13
    hi StatusLine ctermfg=Magenta ctermbg=White cterm=bold,reverse
    hi StatusLineNC ctermfg=Magenta ctermbg=Gray cterm=reverse
    hi TabLine ctermfg=Gray ctermbg=Magenta cterm=NONE
    hi TabLineFill ctermfg=Gray ctermbg=Magenta cterm=NONE
    hi TabLineSel ctermfg=White ctermbg=Magenta cterm=bold
    hi VertSplit ctermfg=Gray ctermbg=Magenta cterm=NONE
    hi WildMenu ctermfg=White ctermbg=DarkYellow cterm=NONE
  elseif s:fc == 14
    hi StatusLine ctermfg=Cyan ctermbg=White cterm=bold,reverse
    hi StatusLineNC ctermfg=Cyan ctermbg=Gray cterm=reverse
    hi TabLine ctermfg=Gray ctermbg=Cyan cterm=NONE
    hi TabLineFill ctermfg=White ctermbg=Cyan cterm=NONE
    hi TabLineSel ctermfg=White ctermbg=Cyan cterm=bold
    hi VertSplit ctermfg=Gray ctermbg=Cyan cterm=NONE
    hi WildMenu ctermfg=White ctermbg=DarkMagenta cterm=bold
  elseif s:fc == 15
    hi StatusLine ctermfg=White ctermbg=Black cterm=bold,reverse
    hi StatusLineNC ctermfg=White ctermbg=DarkGray cterm=reverse
    hi TabLine ctermfg=DarkGray ctermbg=White cterm=NONE
    hi TabLineFill ctermfg=DarkGray ctermbg=White cterm=NONE
    hi TabLineSel ctermfg=Black ctermbg=White cterm=bold
    hi VertSplit ctermfg=DarkGray ctermbg=White cterm=NONE
    hi WildMenu ctermfg=White ctermbg=DarkGray cterm=NONE
  endif
  unlet s:fc
  hi Boolean ctermfg=Green ctermbg=NONE cterm=NONE
  hi Character ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Comment ctermfg=DarkGray ctermbg=NONE cterm=italic
  hi Constant ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Debug ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Delimiter ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi Error ctermfg=DarkRed ctermbg=White cterm=reverse
  hi Float ctermfg=Green ctermbg=NONE cterm=NONE
  hi Function ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Identifier ctermfg=DarkBlue ctermbg=NONE cterm=NONE
  hi Ignore ctermfg=DarkYellow ctermbg=NONE cterm=NONE
  hi Include ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Keyword ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi Label ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Number ctermfg=DarkGreen ctermbg=NONE cterm=NONE
  hi Operator ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi PreProc ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Special ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi SpecialChar ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi SpecialComment ctermfg=DarkMagenta ctermbg=NONE cterm=NONE
  hi Statement ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi StorageClass ctermfg=DarkCyan ctermbg=NONE cterm=NONE
  hi String ctermfg=Red ctermbg=NONE cterm=NONE
  hi Structure ctermfg=DarkRed ctermbg=NONE cterm=NONE
  hi Todo ctermfg=DarkMagenta ctermbg=NONE cterm=bold
  hi Type ctermfg=Blue ctermbg=NONE cterm=NONE
  hi Underlined ctermfg=NONE ctermbg=NONE cterm=underline
  hi CursorIM ctermfg=NONE ctermbg=White cterm=NONE
  hi ToolbarLine ctermfg=DarkGray ctermbg=Gray cterm=NONE
  hi ToolbarButton ctermfg=Black ctermbg=Gray cterm=bold
  hi NormalMode ctermfg=DarkGray ctermbg=White cterm=reverse
  hi InsertMode ctermfg=Green ctermbg=White cterm=reverse
  hi ReplaceMode ctermfg=Red ctermbg=White cterm=reverse
  hi VisualMode ctermfg=DarkBlue ctermbg=White cterm=reverse
  hi CommandMode ctermfg=DarkMagenta ctermbg=White cterm=reverse
  if !s:italics
    hi Comment cterm=NONE
  endif
  if has('nvim')
    hi! link TermCursor Cursor
    hi TermCursorNC ctermfg=White ctermbg=Black cterm=NONE
  endif
  unlet s:t_Co s:italics
  finish
endif

if s:t_Co >= 2
  hi Normal term=NONE
  hi ColorColumn term=reverse
  hi Conceal term=NONE
  hi Cursor term=NONE
  hi CursorColumn term=reverse
  hi CursorLine term=underline
  hi CursorLineNr term=bold,italic,reverse,underline
  hi DiffAdd term=reverse,underline
  hi DiffChange term=reverse,underline
  hi DiffDelete term=reverse,underline
  hi DiffText term=bold,reverse,underline
  hi Directory term=NONE
  hi EndOfBuffer term=NONE
  hi ErrorMsg term=bold,italic,reverse
  hi FoldColumn term=reverse
  hi Folded term=italic,reverse,underline
  hi IncSearch term=bold,italic,reverse
  hi LineNr term=reverse
  hi MatchParen term=bold,underline
  hi ModeMsg term=NONE
  hi MoreMsg term=NONE
  hi NonText term=NONE
  hi Pmenu term=reverse
  hi PmenuSbar term=NONE
  hi PmenuSel term=NONE
  hi PmenuThumb term=NONE
  hi Question term=standout
  hi Search term=italic,underline
  hi SignColumn term=reverse
  hi SpecialKey term=bold
  hi SpellBad term=italic,underline
  hi SpellCap term=italic,underline
  hi SpellLocal term=italic,underline
  hi SpellRare term=italic,underline
  hi StatusLine term=bold,reverse
  hi StatusLineNC term=reverse
  hi TabLine term=italic,reverse,underline
  hi TabLineFill term=reverse,underline
  hi TabLineSel term=bold
  hi Title term=bold
  hi VertSplit term=reverse
  hi Visual term=reverse
  hi VisualNOS term=NONE
  hi WarningMsg term=standout
  hi WildMenu term=bold
  hi Comment term=italic
  hi Constant term=bold,italic
  hi Error term=reverse
  hi Identifier term=italic
  hi Ignore term=NONE
  hi PreProc term=italic
  hi Special term=bold,italic
  hi Statement term=bold
  hi Todo term=bold,underline
  hi Type term=bold
  hi Underlined term=underline
  hi CursorIM term=NONE
  hi ToolbarLine term=reverse
  hi ToolbarButton term=bold,reverse
  if !s:italics
    hi CursorLineNr term=bold,reverse,underline
    hi ErrorMsg term=bold,reverse
    hi Folded term=reverse,underline
    hi IncSearch term=bold,reverse
    hi Search term=underline
    hi SpellBad term=underline
    hi SpellCap term=underline
    hi SpellLocal term=underline
    hi SpellRare term=underline
    hi TabLine term=reverse,underline
    hi Comment term=NONE
    hi Constant term=bold
    hi Identifier term=NONE
    hi PreProc term=NONE
    hi Special term=bold
  endif
  unlet s:t_Co s:italics
  finish
endif

" Color: black         rgb( 95,  95,  97)     59           Black
" Color: red           rgb(232,  80,  63)     167          DarkRed
" Color: green         rgb(  0, 153, 140)     30           DarkGreen
" Color: yellow        rgb(216, 121,   0)     172          DarkYellow
" Color: blue          rgb( 82, 127, 143)     66           DarkBlue
" Color: magenta       rgb(219,  45,  69)     197          DarkMagenta
" Color: cyan          rgb( 21, 156, 204)     74           DarkCyan
" Color: white         rgb(240, 240, 240)     255          Gray
" Color: brightblack   rgb(136, 136, 136)     102          DarkGray
" Color: brightred     rgb(216, 121,   0)     172          Red
" Color: brightgreen   rgb(171, 185, 110)     143          Green
" Color: brightyellow  rgb(225, 173,  11)     178          Yellow
" Color: brightblue    rgb(140,  97, 166)     97           Blue
" Color: brightmagenta rgb(235,  49,  75)     197          Magenta
" Color: brightcyan    rgb( 35, 188, 225)     38           Cyan
" Color: brightwhite   rgb(250, 250, 250)     231          White
" Term Colors: black red green yellow blue magenta cyan white
" Term Colors: brightblack brightred brightgreen brightyellow
" Term Colors: brightblue brightmagenta brightcyan brightwhite
" Background: light
" vim: et ts=2 sw=2
